name: "Source code release"

on:
  push:
    tags:
      - "*"

jobs:

  source-code-release:

    name: "Source code release"
    runs-on: "ubuntu-latest"

    steps:

      - uses: actions/checkout@v2

      - id: get-latest-stable-release
        uses: thebritican/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ github.token }}

      - uses: "mikepenz/release-changelog-builder-action@v3"
        id: github_release
        with:
          configuration: ".changelog.json"
          fromTag: ${{ steps.get-latest-stable-release.outputs.tag_name }}
          toTag: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
