name: "Source code release"

on:
  push:
    tags:
      - "*"

jobs:

  source-code-release:

    name: "Source code release"
    runs-on: "ubuntu-latest"

    steps:

      - uses: actions/checkout@v2

      - uses: "mikepenz/release-changelog-builder-action@v3"
        with:
          configuration: ".changelog.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
