name: "Source code release"

on:
  push:
    tags:
      - "*"

jobs:

  source-code-release:

    name: "Source code release"
    runs-on: "ubuntu-latest"

    steps:

      - uses: actions/checkout@v2

      - id: get-latest-stable-release
        uses: thebritican/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ github.token }}

      - uses: release-drafter/release-drafter@v5
        id: changelog
        with:
          disable-autolabeler: true
          prerelease: false
          tag: ${{ github.ref_name }}
          version: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
