name: "Source code release"

on:
  push:
    tags:
      - "*"

jobs:

  source-code-release:

    name: "Source code release"
    runs-on: "ubuntu-latest"

    steps:

      - uses: actions/checkout@v2

      - id: get-latest-stable-release
        uses: thebritican/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ github.token }}

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "false"
          fallback-version: ${{ steps.get-latest-stable-release.outputs.tag_name }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
