name: Autotest executions

on:
  pull_request:
    branches: [ main ]

jobs:

  pull-requests-autotesting:

    name: "pull-requests-autotesting"
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.5

    - name: Building test environment
      run: bash -c "make env_install_dependencies"

    # - name: Autotesting
    #   env:
    #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AUTH_KEY:  ${{ secrets.AUTH_KEY }}
    #     APP_ENV: test
    #     google_maps_key:  ${{ secrets.GOOGLE_MAPS_KEY }}
    #   run: bash -c "make run_update_kedro_context && make run_test"
